name: Java CI with Maven

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: export QUARKUS_PROFILE=test
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: automerge
        uses: pascalgn/automerge-action@v0.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          MERGE_LABELS: automerge,!work in progress
            MERGE_REMOVE_LABELS: automerge
            MERGE_METHOD: squash
            MERGE_COMMIT_MESSAGE: first test of merging
            MERGE_FORKS: false
            MERGE_RETRIES: 6
            MERGE_RETRY_SLEEP: 10000
            UPDATE_LABELS:
            UPDATE_METHOD: rebase
